# Networking CICD Pipeline with pre-change and post-change validation powered by Nexus Dashboard
name: pipeline-pre

# Controls when the workflow will run
on:
  # Triggers the workflow on push (and merge) events on the master branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# Environment variables
env:
  PYTHONWARNINGS: "ignore:Unverified HTTPS request"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Run lint on the complete directory containint YAML files
  linting:
    runs-on: self-hosted
    container: pmathame/ansible:latest

    steps:
        - uses: actions/checkout@v2
  
        - name: Lint YAML files
          run: yamllint ./data
  
  terraform_plan:
    needs: linting
    runs-on: self-hosted
    container: pmathame/ansible:latest

    steps:
        - uses: actions/checkout@v2

        - name: Terraform Init & Plan
          run: |
            terraform init
            terraform plan -out=plan.tfplan
            terraform show -json plan.tfplan > plan.json

          working-directory: ./

        - name: Pre-change Validation
          run: |
            export PCV_GROUP=default
            export PCV_HOSTNAME_IP=192.168.254.34
            export PCV_PASSWORD=C1sc0123p.
            export PCV_SITE=ACI-BCN
            export PCV_USERNAME=admin
            export no_proxy="192.168.254.34"
            nexus-pcv --name "pcv_${{ github.sha }}" -t plan.json
            
          working-directory: ./

        - name: Upload artifact
          uses: actions/upload-artifact@v2
          with:
            name: plan.json
            path: ./plan.json