# Networking CICD Pipeline with pre-change and post-change validation powered by Nexus Dashboard
name: pipeline-prod

# Controls when the workflow will run
on:
  # Triggers the workflow on push (and merge) events on the master branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# Environment variables
env:
  PYTHONWARNINGS: "ignore:Unverified HTTPS request"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Run lint on the complete directory containint YAML files
 Deploy_Changes:
  runs-on: self-hosted
  container: pmathame/ansible:latest
  steps:
        - uses: actions/checkout@v2

        - name: Terraform Init & Plan & Apply
          run: |
           cp -r /terraform_default/.terraform ./
           terraform init
           terraform plan
           terraform apply -auto-approve
          working-directory: ./

        - name: Send Webex Notification
          uses: adealdag/action-webex-notification@python-v1
          if: always()
          with:
            webexToken: ${{ secrets.WEBEX_TOKEN }}
            roomID: ${{ secrets.ROOM_ID }}
            markdownMsg: |
              ### [${{ github.job }}] ${{ github.repository }} - ${{ github.event.head_commit.message }}
                * Trigger: ${{ github.event_name }}
                * Git SHA: ${{ github.sha }}
                * Status: ${{ job.status }}
                * Details URL: [Nexus Dashboard Insights](${{ secrets.ND_HOST }}/appcenter/cisco/nexus-insights/ui/#/troubleshoot/deltaAnalysis)
### Run post-change validation on Nexus Dashboard Insights
 post-change-validation:
  runs-on: self-hosted
  needs: Deploy_Changes
  container: pmathame/ansible:latest
  steps:
      - uses: actions/checkout@v2
      - name: Run post-change analysis playbook
        run: |
          ansible --version
          rm -rf $HOME/.ansible/pc
          ansible-playbook -i inventory.yaml post-change-validation.yaml
          working-directory: tools/change-validation

      - name: Send Webex Notification
        uses: adealdag/action-webex-notification@python-v1
        if: always()
        with:
          webexToken: ${{ secrets.WEBEX_TOKEN }}
          roomID: ${{ secrets.ROOM_ID }}
          markdownMsg: |
            ### [${{ github.job }}] ${{ github.repository }} - ${{ github.event.head_commit.message }}
              * Trigger: ${{ github.event_name }}
              * Git SHA: ${{ github.sha }}
              * Status: ${{ job.status }}
              * Details URL: [Nexus Dashboard Insights](${{ secrets.ND_HOST }}/appcenter/cisco/nexus-insights/ui/#/troubleshoot/deltaAnalysis)